manifest:
  remotes:
    - name: cyanindya
      url-base: https://github.com/cyanindya
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk-keyboard-skeletyl-handwired
      remote: cyanindya
      revision: main
      import: west.yml
  self:
    path: config