manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: cyanindya
      url-base: https://github.com/cyanindya
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-keyboard-skeletyl-handwired
      remote: cyanindya
      revision: main
      # import: west.yml
  self:
    path: config